### ISSUE TITLE
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index', 'flax_model.msgpack'] found in directory ../models/DistilBert or `from_tf` and `from_flax` set to False.

### ISSUE THREAD

**Issue by Varunvora18** [fidelity/classitransformers#5]
Do we need to download the files from https://huggingface.co/bert-base-uncased/tree/main It still does not have model.ckpt.index. Where do we download that from?

**Comment by abhijeet3922** [comment]
Hi,

The models has to be downloaded before finetuning.

Pls. refer this. 
https://github.com/fidelity/classitransformers#getting-language-models

**Comment by Varunvora18** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-60b4be9cf802> in <module>
      4 from classitransformers.configs import Configs
      5 
----> 6 from classitransformers.tfbert import BertClassification

D:\INIT\InIT Stock Prediction Project\classitransformers\classitransformers\tfbert.py in <module>
     18 from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix
     19 
---> 20 from bert import modeling
     21 from bert import optimization
     22 from bert import tokenization

~\anaconda3new\envs\env\lib\site-packages\bert\modeling.py in <module>
     27 import six
     28 import tensorflow.compat.v1 as tf
---> 29 from tensorflow.contrib import layers as contrib_layers
     30 
     31 

ModuleNotFoundError: No module named 'tensorflow.contrib'

Any idea what to replace the code in the notebook "TF_classi_transformers_sentiment_example" with?

**Comment by abhijeet3922** [comment]
Seems like you have to install tensorflow.contrib
Check [this](https://stackoverflow.com/questions/59843037/no-module-named-tensorflow-contrib)

The package is written using tensorflow 1.x.x version.
